# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.dashboard_count_data_campaigns_by_status import DashboardCountDataCampaignsByStatus

class TestDashboardCountDataCampaignsByStatus(unittest.TestCase):
    """DashboardCountDataCampaignsByStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardCountDataCampaignsByStatus:
        """Test DashboardCountDataCampaignsByStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardCountDataCampaignsByStatus`
        """
        model = DashboardCountDataCampaignsByStatus()
        if include_optional:
            return DashboardCountDataCampaignsByStatus(
                draft = 56
            )
        else:
            return DashboardCountDataCampaignsByStatus(
        )
        """

    def testDashboardCountDataCampaignsByStatus(self):
        """Test DashboardCountDataCampaignsByStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
