# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.subscriber_query_request import SubscriberQueryRequest

class TestSubscriberQueryRequest(unittest.TestCase):
    """SubscriberQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriberQueryRequest:
        """Test SubscriberQueryRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriberQueryRequest`
        """
        model = SubscriberQueryRequest()
        if include_optional:
            return SubscriberQueryRequest(
                query = '',
                ids = [
                    56
                    ],
                action = 'add',
                target_list_ids = [
                    56
                    ],
                status = 'confirmed'
            )
        else:
            return SubscriberQueryRequest(
        )
        """

    def testSubscriberQueryRequest(self):
        """Test SubscriberQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
