# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk.models.campaign_update import CampaignUpdate

class TestCampaignUpdate(unittest.TestCase):
    """CampaignUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CampaignUpdate:
        """Test CampaignUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CampaignUpdate`
        """
        model = CampaignUpdate()
        if include_optional:
            return CampaignUpdate(
                name = '',
                subject = '',
                lists = [
                    56
                    ],
                from_email = '',
                messenger = '',
                type = '',
                tags = [
                    ''
                    ],
                send_later = True,
                send_at = None,
                headers = [
                    None
                    ],
                template_id = 56,
                content_type = '',
                body = '',
                altbody = '',
                archive = True,
                archive_template_id = 56,
                archive_meta = None
            )
        else:
            return CampaignUpdate(
        )
        """

    def testCampaignUpdate(self):
        """Test CampaignUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
