# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.subscriber_data import SubscriberData

class TestSubscriberData(unittest.TestCase):
    """SubscriberData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriberData:
        """Test SubscriberData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriberData`
        """
        model = SubscriberData()
        if include_optional:
            return SubscriberData(
                email = '',
                profile = [
                    listmonk_client.models.subscriber_profile.SubscriberProfile(
                        id = 56, 
                        uuid = '', 
                        email = '', 
                        name = '', 
                        attribs = listmonk_client.models.subscriber_profile_attribs.SubscriberProfile_attribs(
                            city = '', 
                            good = True, 
                            type = '', ), 
                        status = '', 
                        created_at = '', 
                        updated_at = '', )
                    ],
                subscriptions = [
                    listmonk_client.models.subscriptions.Subscriptions(
                        subscription_status = '', 
                        name = '', 
                        type = '', 
                        created_at = '', )
                    ],
                campaign_views = [
                    None
                    ],
                link_clicks = [
                    None
                    ]
            )
        else:
            return SubscriberData(
        )
        """

    def testSubscriberData(self):
        """Test SubscriberData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
