# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.get_campaign_analytics200_response import GetCampaignAnalytics200Response

class TestGetCampaignAnalytics200Response(unittest.TestCase):
    """GetCampaignAnalytics200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCampaignAnalytics200Response:
        """Test GetCampaignAnalytics200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCampaignAnalytics200Response`
        """
        model = GetCampaignAnalytics200Response()
        if include_optional:
            return GetCampaignAnalytics200Response(
                data = [
                    listmonk.models.campaign_analytics_count.CampaignAnalyticsCount(
                        campaign_id = 56, 
                        count = 56, 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return GetCampaignAnalytics200Response(
        )
        """

    def testGetCampaignAnalytics200Response(self):
        """Test GetCampaignAnalytics200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
