# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.get_running_campaign_stats200_response import GetRunningCampaignStats200Response

class TestGetRunningCampaignStats200Response(unittest.TestCase):
    """GetRunningCampaignStats200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRunningCampaignStats200Response:
        """Test GetRunningCampaignStats200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRunningCampaignStats200Response`
        """
        model = GetRunningCampaignStats200Response()
        if include_optional:
            return GetRunningCampaignStats200Response(
                data = [
                    listmonk.models.campaign_stats.CampaignStats(
                        id = 56, 
                        status = '', 
                        to_send = 56, 
                        sent = 56, 
                        started_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        updated_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        rate = 56, 
                        net_rate = 56, )
                    ]
            )
        else:
            return GetRunningCampaignStats200Response(
        )
        """

    def testGetRunningCampaignStats200Response(self):
        """Test GetRunningCampaignStats200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
