# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from listmonk_client.api.import_api import ImportApi


class TestImportApi(unittest.TestCase):
    """ImportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImportApi()

    def tearDown(self) -> None:
        pass

    def test_get_import_subscriber_stats(self) -> None:
        """Test case for get_import_subscriber_stats

        """
        pass

    def test_get_import_subscribers(self) -> None:
        """Test case for get_import_subscribers

        """
        pass

    def test_import_subscribers(self) -> None:
        """Test case for import_subscribers

        """
        pass

    def test_stop_import_subscribers(self) -> None:
        """Test case for stop_import_subscribers

        """
        pass


if __name__ == '__main__':
    unittest.main()
