# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.delete_gc_subscribers200_response import DeleteGCSubscribers200Response

class TestDeleteGCSubscribers200Response(unittest.TestCase):
    """DeleteGCSubscribers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteGCSubscribers200Response:
        """Test DeleteGCSubscribers200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteGCSubscribers200Response`
        """
        model = DeleteGCSubscribers200Response()
        if include_optional:
            return DeleteGCSubscribers200Response(
                data = listmonk_client.models.delete_gc_subscribers_200_response_data.deleteGCSubscribers_200_response_data(
                    count = 56, )
            )
        else:
            return DeleteGCSubscribers200Response(
        )
        """

    def testDeleteGCSubscribers200Response(self):
        """Test DeleteGCSubscribers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
