# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from listmonk.api.campaigns_api import CampaignsApi


class TestCampaignsApi(unittest.TestCase):
    """CampaignsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CampaignsApi()

    def tearDown(self) -> None:
        pass

    def test_create_campaign(self) -> None:
        """Test case for create_campaign

        """
        pass

    def test_create_campaign_content_by_id(self) -> None:
        """Test case for create_campaign_content_by_id

        """
        pass

    def test_delete_campaign_by_id(self) -> None:
        """Test case for delete_campaign_by_id

        """
        pass

    def test_get_campaign_analytics(self) -> None:
        """Test case for get_campaign_analytics

        """
        pass

    def test_get_campaign_by_id(self) -> None:
        """Test case for get_campaign_by_id

        """
        pass

    def test_get_campaigns(self) -> None:
        """Test case for get_campaigns

        """
        pass

    def test_get_running_campaign_stats(self) -> None:
        """Test case for get_running_campaign_stats

        """
        pass

    def test_preview_campaign_by_id(self) -> None:
        """Test case for preview_campaign_by_id

        """
        pass

    def test_preview_campaign_text_by_id(self) -> None:
        """Test case for preview_campaign_text_by_id

        """
        pass

    def test_test_campaign_by_id(self) -> None:
        """Test case for test_campaign_by_id

        """
        pass

    def test_update_campaign_archive_by_id(self) -> None:
        """Test case for update_campaign_archive_by_id

        """
        pass

    def test_update_campaign_by_id(self) -> None:
        """Test case for update_campaign_by_id

        """
        pass

    def test_update_campaign_status_by_id(self) -> None:
        """Test case for update_campaign_status_by_id

        """
        pass

    def test_update_preview_campaign_by_id(self) -> None:
        """Test case for update_preview_campaign_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
