# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.get_import_subscriber_stats200_response import GetImportSubscriberStats200Response

class TestGetImportSubscriberStats200Response(unittest.TestCase):
    """GetImportSubscriberStats200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetImportSubscriberStats200Response:
        """Test GetImportSubscriberStats200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetImportSubscriberStats200Response`
        """
        model = GetImportSubscriberStats200Response()
        if include_optional:
            return GetImportSubscriberStats200Response(
                data = ''
            )
        else:
            return GetImportSubscriberStats200Response(
        )
        """

    def testGetImportSubscriberStats200Response(self):
        """Test GetImportSubscriberStats200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
