# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk.models.get_logs200_response import GetLogs200Response

class TestGetLogs200Response(unittest.TestCase):
    """GetLogs200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLogs200Response:
        """Test GetLogs200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLogs200Response`
        """
        model = GetLogs200Response()
        if include_optional:
            return GetLogs200Response(
                data = [
                    ''
                    ]
            )
        else:
            return GetLogs200Response(
        )
        """

    def testGetLogs200Response(self):
        """Test GetLogs200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
