# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.subscriber_profile import SubscriberProfile

class TestSubscriberProfile(unittest.TestCase):
    """SubscriberProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriberProfile:
        """Test SubscriberProfile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriberProfile`
        """
        model = SubscriberProfile()
        if include_optional:
            return SubscriberProfile(
                id = 56,
                uuid = '',
                email = '',
                name = '',
                attribs = listmonk.models.subscriber_profile_attribs.SubscriberProfile_attribs(
                    city = '', 
                    good = True, 
                    type = '', ),
                status = '',
                created_at = '',
                updated_at = ''
            )
        else:
            return SubscriberProfile(
        )
        """

    def testSubscriberProfile(self):
        """Test SubscriberProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
