# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk.models.get_health_check200_response import GetHealthCheck200Response

class TestGetHealthCheck200Response(unittest.TestCase):
    """GetHealthCheck200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHealthCheck200Response:
        """Test GetHealthCheck200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHealthCheck200Response`
        """
        model = GetHealthCheck200Response()
        if include_optional:
            return GetHealthCheck200Response(
                data = True
            )
        else:
            return GetHealthCheck200Response(
        )
        """

    def testGetHealthCheck200Response(self):
        """Test GetHealthCheck200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
