# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.delete_gc_subscribers200_response_data import DeleteGCSubscribers200ResponseData

class TestDeleteGCSubscribers200ResponseData(unittest.TestCase):
    """DeleteGCSubscribers200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteGCSubscribers200ResponseData:
        """Test DeleteGCSubscribers200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteGCSubscribers200ResponseData`
        """
        model = DeleteGCSubscribers200ResponseData()
        if include_optional:
            return DeleteGCSubscribers200ResponseData(
                count = 56
            )
        else:
            return DeleteGCSubscribers200ResponseData(
        )
        """

    def testDeleteGCSubscribers200ResponseData(self):
        """Test DeleteGCSubscribers200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
