# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.handle_public_subscription200_response import HandlePublicSubscription200Response

class TestHandlePublicSubscription200Response(unittest.TestCase):
    """HandlePublicSubscription200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlePublicSubscription200Response:
        """Test HandlePublicSubscription200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlePublicSubscription200Response`
        """
        model = HandlePublicSubscription200Response()
        if include_optional:
            return HandlePublicSubscription200Response(
                has_optin = True
            )
        else:
            return HandlePublicSubscription200Response(
        )
        """

    def testHandlePublicSubscription200Response(self):
        """Test HandlePublicSubscription200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
