# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.get_subscriber_bounces_by_id200_response import GetSubscriberBouncesById200Response

class TestGetSubscriberBouncesById200Response(unittest.TestCase):
    """GetSubscriberBouncesById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSubscriberBouncesById200Response:
        """Test GetSubscriberBouncesById200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSubscriberBouncesById200Response`
        """
        model = GetSubscriberBouncesById200Response()
        if include_optional:
            return GetSubscriberBouncesById200Response(
                data = [
                    listmonk.models.bounce.Bounce(
                        results = [
                            listmonk.models.bounce_results_inner.Bounce_results_inner(
                                id = 56, 
                                type = '', 
                                source = '', 
                                meta = listmonk.models.meta.meta(),
                                created_at = '', 
                                email = '', 
                                subscriber_uuid = '', 
                                subscriber_id = 56, 
                                campaign = listmonk.models.bounce_results_inner_campaign.Bounce_results_inner_campaign(
                                    id = 56, 
                                    name = '', ), 
                                campaign_uuid = '', 
                                total = 56, )
                            ], )
                    ]
            )
        else:
            return GetSubscriberBouncesById200Response(
        )
        """

    def testGetSubscriberBouncesById200Response(self):
        """Test GetSubscriberBouncesById200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
