# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from listmonk.api.logs_api import LogsApi


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LogsApi()

    def tearDown(self) -> None:
        pass

    def test_get_logs(self) -> None:
        """Test case for get_logs

        """
        pass


if __name__ == '__main__':
    unittest.main()
