# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk.models.campaign_stats import CampaignStats

class TestCampaignStats(unittest.TestCase):
    """CampaignStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CampaignStats:
        """Test CampaignStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CampaignStats`
        """
        model = CampaignStats()
        if include_optional:
            return CampaignStats(
                id = 56,
                status = '',
                to_send = 56,
                sent = 56,
                started_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                updated_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                rate = 56,
                net_rate = 56
            )
        else:
            return CampaignStats(
        )
        """

    def testCampaignStats(self):
        """Test CampaignStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
