# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.dashboard_count_data_campaigns import DashboardCountDataCampaigns

class TestDashboardCountDataCampaigns(unittest.TestCase):
    """DashboardCountDataCampaigns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardCountDataCampaigns:
        """Test DashboardCountDataCampaigns
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardCountDataCampaigns`
        """
        model = DashboardCountDataCampaigns()
        if include_optional:
            return DashboardCountDataCampaigns(
                total = 56,
                by_status = listmonk.models.dashboard_count_data_campaigns_by_status.DashboardCount_data_campaigns_by_status(
                    draft = 56, )
            )
        else:
            return DashboardCountDataCampaigns(
        )
        """

    def testDashboardCountDataCampaigns(self):
        """Test DashboardCountDataCampaigns"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
