# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.campaign_request_send_at import CampaignRequestSendAt

class TestCampaignRequestSendAt(unittest.TestCase):
    """CampaignRequestSendAt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CampaignRequestSendAt:
        """Test CampaignRequestSendAt
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CampaignRequestSendAt`
        """
        model = CampaignRequestSendAt()
        if include_optional:
            return CampaignRequestSendAt(
                headers = [
                    None
                    ],
                template_id = 1.337
            )
        else:
            return CampaignRequestSendAt(
        )
        """

    def testCampaignRequestSendAt(self):
        """Test CampaignRequestSendAt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
