# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from listmonk.api.transactional_api import TransactionalApi


class TestTransactionalApi(unittest.TestCase):
    """TransactionalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionalApi()

    def tearDown(self) -> None:
        pass

    def test_transact_with_subscriber(self) -> None:
        """Test case for transact_with_subscriber

        """
        pass


if __name__ == '__main__':
    unittest.main()
