# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.get_settings200_response import GetSettings200Response

class TestGetSettings200Response(unittest.TestCase):
    """GetSettings200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSettings200Response:
        """Test GetSettings200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSettings200Response`
        """
        model = GetSettings200Response()
        if include_optional:
            return GetSettings200Response(
                data = listmonk_client.models.settings.Settings(
                    app/site_name = '', 
                    app/root_url = '', 
                    app/logo_url = '', 
                    app/favicon_url = '', 
                    app/from_email = '', 
                    app/notify_emails = [
                        ''
                        ], 
                    app/enable_public_subscription_page = True, 
                    app/enable_public_archive = True, 
                    app/send_optin_confirmation = True, 
                    app/check_updates = True, 
                    app/lang = '', 
                    app/batch_size = 56, 
                    app/concurrency = 56, 
                    app/max_send_errors = 56, 
                    app/message_rate = 56, 
                    app/message_sliding_window = True, 
                    app/message_sliding_window_duration = '', 
                    app/message_sliding_window_rate = 56, 
                    privacy/individual_tracking = True, 
                    privacy/unsubscribe_header = True, 
                    privacy/allow_blocklist = True, 
                    privacy/allow_preferences = True, 
                    privacy/allow_export = True, 
                    privacy/allow_wipe = True, 
                    privacy/exportable = [
                        ''
                        ], 
                    privacy/domain_blocklist = [
                        None
                        ], 
                    upload/provider = '', 
                    upload/filesystem/upload_path = '', 
                    upload/filesystem/upload_uri = '', 
                    upload/s3/url = '', 
                    upload/s3/public_url = '', 
                    upload/s3/aws_access_key_id = '', 
                    upload/s3/aws_default_region = '', 
                    upload/s3/bucket = '', 
                    upload/s3/bucket_domain = '', 
                    upload/s3/bucket_path = '', 
                    upload/s3/bucket_type = '', 
                    upload/s3/expiry = '', 
                    smtp = [
                        listmonk_client.models.smtp_settings.SMTPSettings(
                            uuid = '', 
                            enabled = True, 
                            host = '', 
                            hello_hostname = '', 
                            port = 56, 
                            auth_protocol = '', 
                            username = '', 
                            email_headers = [
                                None
                                ], 
                            max_conns = 56, 
                            max_msg_retries = 56, 
                            idle_timeout = '', 
                            wait_timeout = '', 
                            tls_type = '', 
                            tls_skip_verify = True, )
                        ], 
                    messengers = [
                        None
                        ], 
                    bounce/enabled = True, 
                    bounce/webhooks_enabled = True, 
                    bounce/count = 56, 
                    bounce/action = '', 
                    bounce/ses_enabled = True, 
                    bounce/sendgrid_enabled = True, 
                    bounce/sendgrid_key = '', 
                    bounce/postmark_enabled = True, 
                    bounce/postmark_username = '', 
                    bounce/postmark_password = '', 
                    bounce/mailboxes = [
                        listmonk_client.models.mail_box_bounces.MailBoxBounces(
                            uuid = '', 
                            enabled = True, 
                            type = '', 
                            host = '', 
                            port = 56, 
                            auth_protocol = '', 
                            return_path = '', 
                            username = '', 
                            tls_enabled = True, 
                            tls_skip_verify = True, 
                            scan_interval = '', )
                        ], 
                    appearance/admin/custom_css = '', 
                    appearance/admin/custom_js = '', 
                    appearance/public/custom_css = '', 
                    appearance/public/custom_js = '', )
            )
        else:
            return GetSettings200Response(
        )
        """

    def testGetSettings200Response(self):
        """Test GetSettings200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
