# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk.models.get_public_lists200_response_inner import GetPublicLists200ResponseInner

class TestGetPublicLists200ResponseInner(unittest.TestCase):
    """GetPublicLists200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPublicLists200ResponseInner:
        """Test GetPublicLists200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPublicLists200ResponseInner`
        """
        model = GetPublicLists200ResponseInner()
        if include_optional:
            return GetPublicLists200ResponseInner(
                uuid = '',
                name = ''
            )
        else:
            return GetPublicLists200ResponseInner(
        )
        """

    def testGetPublicLists200ResponseInner(self):
        """Test GetPublicLists200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
