# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from listmonk_client.api.miscellaneous_api import MiscellaneousApi


class TestMiscellaneousApi(unittest.TestCase):
    """MiscellaneousApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MiscellaneousApi()

    def tearDown(self) -> None:
        pass

    def test_get_dashboard_charts(self) -> None:
        """Test case for get_dashboard_charts

        """
        pass

    def test_get_dashboard_counts(self) -> None:
        """Test case for get_dashboard_counts

        """
        pass

    def test_get_health_check(self) -> None:
        """Test case for get_health_check

        """
        pass

    def test_get_i18n_lang(self) -> None:
        """Test case for get_i18n_lang

        """
        pass

    def test_get_server_config(self) -> None:
        """Test case for get_server_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
