# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from listmonk.api.bounces_api import BouncesApi


class TestBouncesApi(unittest.TestCase):
    """BouncesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BouncesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_bounce_by_id(self) -> None:
        """Test case for delete_bounce_by_id

        """
        pass

    def test_delete_bounces(self) -> None:
        """Test case for delete_bounces

        """
        pass

    def test_get_bounce_by_id(self) -> None:
        """Test case for get_bounce_by_id

        """
        pass

    def test_get_bounces(self) -> None:
        """Test case for get_bounces

        """
        pass


if __name__ == '__main__':
    unittest.main()
