# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from listmonk_client.api.templates_api import TemplatesApi


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_template_by_id(self) -> None:
        """Test case for delete_template_by_id

        """
        pass

    def test_get_template_by_id(self) -> None:
        """Test case for get_template_by_id

        """
        pass

    def test_get_templates(self) -> None:
        """Test case for get_templates

        """
        pass

    def test_preview_template(self) -> None:
        """Test case for preview_template

        """
        pass

    def test_preview_template_by_id(self) -> None:
        """Test case for preview_template_by_id

        """
        pass

    def test_update_template_by_id(self) -> None:
        """Test case for update_template_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
