# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.get_import_subscribers200_response import GetImportSubscribers200Response

class TestGetImportSubscribers200Response(unittest.TestCase):
    """GetImportSubscribers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetImportSubscribers200Response:
        """Test GetImportSubscribers200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetImportSubscribers200Response`
        """
        model = GetImportSubscribers200Response()
        if include_optional:
            return GetImportSubscribers200Response(
                data = listmonk.models.import_status.ImportStatus(
                    data = listmonk.models.import_status_data.ImportStatus_data(
                        name = '', 
                        total = 56, 
                        imported = 56, 
                        status = '', ), )
            )
        else:
            return GetImportSubscribers200Response(
        )
        """

    def testGetImportSubscribers200Response(self):
        """Test GetImportSubscribers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
