# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk.models.server_config import ServerConfig

class TestServerConfig(unittest.TestCase):
    """ServerConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerConfig:
        """Test ServerConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerConfig`
        """
        model = ServerConfig()
        if include_optional:
            return ServerConfig(
                data = listmonk.models.server_config_data.ServerConfig_data(
                    messengers = [
                        ''
                        ], 
                    langs = [
                        listmonk.models.server_config_data_langs_inner.ServerConfig_data_langs_inner(
                            code = '', 
                            name = '', )
                        ], 
                    lang = '', 
                    update = '', 
                    needs_restart = True, 
                    version = '', )
            )
        else:
            return ServerConfig(
        )
        """

    def testServerConfig(self):
        """Test ServerConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
