# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from listmonk_client.api.media_api import MediaApi


class TestMediaApi(unittest.TestCase):
    """MediaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MediaApi()

    def tearDown(self) -> None:
        pass

    def test_delete_media_by_id(self) -> None:
        """Test case for delete_media_by_id

        """
        pass

    def test_get_media(self) -> None:
        """Test case for get_media

        """
        pass

    def test_get_media_by_id(self) -> None:
        """Test case for get_media_by_id

        """
        pass

    def test_upload_media(self) -> None:
        """Test case for upload_media

        """
        pass


if __name__ == '__main__':
    unittest.main()
