# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.mail_box_bounces import MailBoxBounces

class TestMailBoxBounces(unittest.TestCase):
    """MailBoxBounces unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailBoxBounces:
        """Test MailBoxBounces
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailBoxBounces`
        """
        model = MailBoxBounces()
        if include_optional:
            return MailBoxBounces(
                uuid = '',
                enabled = True,
                type = '',
                host = '',
                port = 56,
                auth_protocol = '',
                return_path = '',
                username = '',
                tls_enabled = True,
                tls_skip_verify = True,
                scan_interval = ''
            )
        else:
            return MailBoxBounces(
        )
        """

    def testMailBoxBounces(self):
        """Test MailBoxBounces"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
