# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.dashboard_count_data_lists import DashboardCountDataLists

class TestDashboardCountDataLists(unittest.TestCase):
    """DashboardCountDataLists unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardCountDataLists:
        """Test DashboardCountDataLists
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardCountDataLists`
        """
        model = DashboardCountDataLists()
        if include_optional:
            return DashboardCountDataLists(
                total = 56,
                private = 56,
                public = 56,
                optin_single = 56,
                optin_double = 56
            )
        else:
            return DashboardCountDataLists(
        )
        """

    def testDashboardCountDataLists(self):
        """Test DashboardCountDataLists"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
