# coding: utf-8

"""
    Listmonk

    The API collection for listmonk

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from listmonk_client.models.create_campaign200_response import CreateCampaign200Response

class TestCreateCampaign200Response(unittest.TestCase):
    """CreateCampaign200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCampaign200Response:
        """Test CreateCampaign200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCampaign200Response`
        """
        model = CreateCampaign200Response()
        if include_optional:
            return CreateCampaign200Response(
                data = listmonk_client.models.campaign_update.CampaignUpdate(
                    name = '', 
                    subject = '', 
                    lists = [
                        56
                        ], 
                    from_email = '', 
                    messenger = '', 
                    type = '', 
                    tags = [
                        ''
                        ], 
                    send_later = True, 
                    send_at = listmonk_client.models.send_at.send_at(),
                    headers = [
                        None
                        ], 
                    template_id = 56, 
                    content_type = '', 
                    body = '', 
                    altbody = '', 
                    archive = True, 
                    archive_template_id = 56, 
                    archive_meta = listmonk_client.models.archive_meta.archive_meta(), )
            )
        else:
            return CreateCampaign200Response(
        )
        """

    def testCreateCampaign200Response(self):
        """Test CreateCampaign200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
